# Generated by Django 3.0.8 on 2020-07-27 15:32

import datetime
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('exercise_start', models.DateTimeField(default=datetime.datetime.now)),
                ('scenario_start', models.DurationField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_display_name', models.CharField(max_length=200)),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='world.WorldBorder')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario.Scenario')),
            ],
        ),
        migrations.CreateModel(
            name='Wave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_delta', models.DurationField(default=datetime.timedelta(0))),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario.Scenario')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_display_name', models.CharField(max_length=200)),
                ('true_launch_location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0, srid=4326), srid=4326)),
                ('observed_launch_location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('launch_delta', models.DurationField(default=datetime.timedelta(0))),
                ('observed_launch_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='world.WorldBorder')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario.Vehicle')),
                ('wave', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scenario.Wave')),
            ],
        ),
        migrations.CreateModel(
            name='Warhead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warhead_yield', models.FloatField()),
                ('true_impact_location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0, srid=4326), srid=4326)),
                ('observed_impact_location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('impact_delta', models.DurationField(default=datetime.timedelta(0))),
                ('observed_impact_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='world.WorldBorder')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario.Weapon')),
            ],
        ),
    ]
