# Generated by Django 3.0.8 on 2020-07-28 16:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
        ('scenario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='observed_launch_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.WorldBorder'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='observed_launch_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
