# Generated by Django 3.0.8 on 2020-07-23 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warhead',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario.Weapon'),
        ),
    ]
