# Generated by Django 3.0.8 on 2020-07-29 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
        ('scenario', '0002_auto_20200728_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warhead',
            name='observed_impact_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.WorldBorder'),
        ),
    ]
