# Generated by Django 3.0.8 on 2020-07-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0002_auto_20200723_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='warhead',
            name='warhead_yield',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
