# Generated by Django 3.0.8 on 2020-07-29 16:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0003_auto_20200729_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warhead',
            name='observed_impact_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
