# Generated by Django 3.0.8 on 2020-07-29 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0004_auto_20200729_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warhead',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warheads', to='scenario.Weapon'),
        ),
    ]
