# Generated by Django 3.0.8 on 2020-07-29 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0006_auto_20200729_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='scenario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scenario.Scenario'),
        ),
    ]
