# Generated by Django 3.0.8 on 2020-07-29 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
        ('scenario', '0007_weapon_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='world.WorldBorder'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='observed_launch_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='world.WorldBorder'),
        ),
    ]
