# Generated by Django 3.0.8 on 2020-07-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0008_auto_20200729_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='warhead',
            name='target_display_name',
            field=models.CharField(default='Unknown Target', max_length=200),
        ),
    ]
